version: '3.1'
services:
  # *******************APP**********************
  app:
    container_name: myapp
    image: myapp
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql

      # *****************POSTGRESQL************************
  dbpostgresql:
    image: postgres:11
    container_name: postgres_11
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5435
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    restart: unless-stopped

volumes:
  postgres-data:

